### ISSUE TITLE
Kodi Flatpak install - MPRIS not working

### ISSUE THREAD

**Issue by marekmosiewicz** [wastis/MediaPlayerRemoteInterface#3] opened 2023-05-03 10:20 UTC
I have installed Kodi from Fedora Flatpak, installed Linux Kodi repository and this add-on and playerctl. However media buttons do not work and when I run `playerctl -p kodi next playerctl` says that no player is found. `playerctl -l` displays only rhytmbox as player

**Comment by marekmosiewicz** [comment] 2023-05-03 17:56
Version of kodi from RPM Fusion works correctly

**Comment by wastis** [comment] 2023-05-04 07:05
Thank you for highlighting.
I had a quick look to the issue. Problem is that Flatpak uses a different environment. 
1. home directory is on a different location. As a work around this could be resolved by linking ~/.kodi to .var/app/tv.kodi.Kodi/data
2. specific dbus service is not found. I guess this is due to sandbox access limitation of flatpak. [flatpak sandbox](https://docs.flatpak.org/en/latest/sandbox-permissions.html)  To overcome this, a little bit more investigation has to be done, unfortunately my time is limited now. 

This is reported in kodi debug-log with script location, if anyone want to troubleshoot. 

If I find some time, I will work on this, however given the limited usefulness of this project (9 star at this point), it has low priority for me.

**Comment by marekmosiewicz** [comment] 2023-05-05 17:01
I think project is not well known. I seen questions concerning working media keys in Linux on Kodi forum but people try different strange things like defining keyboard layout (I think it could work only with Kodi having focus). It took me some time that I need to install playerctl and install this add-on (first trying with flatpak which did not work).

**Comment by marekmosiewicz** [comment] 2023-05-05 17:37
I seen your post https://forum.kodi.tv/showthread.php?tid=352804&page=2 . For me at least on Fedora you also need to install playerctl

**Comment by wastis** [comment] 2023-05-06 05:04
I did test the kodi flatpak install on linux mint, same issue. 
playerctl is just a mpris client and therefore should not influence the functioning of the mrpis server of this addon at all. I will check this.

**Comment by wastis** [comment] 2023-05-06 06:50
At the end, the solution is quite simple. It is a matter to grant flatpak kodi sandbox access to the session-bus in order to access the mrpis namespace. This should be build into the flatpak Kodi install by default.

`sudo flatpak override --socket=session-bus tv.kodi.Kodi`

**Closed as completed by wastis** 2023-05-06 06:50 UTC

**Comment by Sanfe** [comment] 2024-12-29 13:43
Its extrange.  Steam deck in desktop mode works all except pause. Also, when i stop, the MPRIS restart the channel. In game mode with decky music mpris plugin works. How i could make that pause work? i made all the fix of this post.


![image](https://github.com/user-attachments/assets/bc8634ba-8a72-4d87-a22f-32b96d24429d)

**Comment by wastis** [comment] 2024-12-29 15:22
If all keys work except for the "Pause" key, it would indicate a key mapping problem rather than an issue with Flatpak access rights. Upon examining the source code of the MPRIS interface, I confirmed that the "Pause" key is forwarded to Kodi as is. 

Since the "Pause" key functions correctly in game mode but not in desktop mode, it suggests that there is a switch between key maps when changing modes. This is where I would start my investigation. 

To eliminate the potential issue that Kodi is not understanding the Pause key, you could try setting the "Pause" key to function as "Play/Pause," with "play_pause"-key, similar to how the "Play/Pause" key is configured in your setup. 

Unfortunately, I do not have a Steam Deck, so I am unable to troubleshoot this directly.

**Comment by maksz42** [comment] 2025-01-11 11:13
On Kubuntu 22.04 with Kodi from Flatpak, the pause button also doesn't work. Maybe it's something about KDE?
Another thing I noticed is that Firefox's media controls are available in the task bar, but Kodi's aren't, although Kodi is present in the media panel.
![Screenshot_20250111_115447](https://github.com/user-attachments/assets/dc875ac5-70b5-4896-ad41-58f19590477a)
![Screenshot_20250111_115738](https://github.com/user-attachments/assets/0cd70d27-2a3b-41c2-ad09-fffa381fdec0)
![Screenshot_20250111_115908](https://github.com/user-attachments/assets/df19e2a9-177a-4331-8afc-008fae1870d0)

**Comment by wastis** [comment] 2025-01-11 20:03
OK, I did install kubuntu 22.04 and indeed it seems to be a problem there. Instead on sending a play_pause command when pressing the Play/Pause key, it sends a just a "pause" from the OS, which kodi does not seem to understand. 

I did upload an updated version 1.0.7 to fix this.

**Comment by wastis** [comment] 2025-01-11 20:05
The other problem with the media panel, I cannot reproduce. This is most likely a KDE problem or the image has a broken/ wrong format.
